### ISSUE TITLE
OGR/GDAL in Metwork 1.0 - PostgresSQL not found

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfext#1009]
**In Metwork 1.0, OGR/GDAL is not compiled with Postgresql driver.**

`ogrinfo list | grep -i postgres` returns nothing

**In Metwork 0.x, OGR/GDAL is compiled with Postgresql driver.**

`ogrinfo list | grep -i postgres` returns  `-> PostgreSQL`

Is there a workaround while waiting for the fix to be available ?

**Comment by thebaptiste** [comment]
Yes it's a mfext issue, I transferred it.
It's strange because GDAL is built, as in 0.9, with option `--with-pg`.
I will try to solve it as soon as possible.
I don't think there is any workaround...

**Comment by thebaptiste** [comment]
With gdal release used for Metwork 0.9 `--with-pg` was a path to pg_config. With gdal 3.0.2 for Metwork 1.0 we must use `with-pg=yes`. Sorry I didn't see that.
I will soon have a fix.

**Comment by thebaptiste** [comment]
And I will add an integration test to check gdal supports

**Comment by dearith** [comment]
OK. Thanks.

**Comment by thebaptiste** [comment]
The fix is in the pipe and should be available in the afternoon or at the lastest tomorrow morning.
Thanks (once again) for your reporting.

**Comment by dearith** [comment]
I'm working with Metwork 1.0 from the http://metwork-framework.org/pub/metwork/releases/rpms/release_1.0/portable/ repository (and not from continuous integration).

This http://metwork-framework.org/pub/metwork/releases/rpms/release_1.0/portable/ repo has not been updated since 2020/11/03. Could you tell me when  new releases with all issues fixed since this date will be available ?

**Comment by thebaptiste** [comment]
Maybe you should rather use http://metwork-framework.org/pub/metwork/continuous_integration/rpms/release_1.0/portable/ which is updated much more frequently. @thefab ?

**Comment by thebaptiste** [comment]
@thefab has just told me we are going to release new versions tomorrow on http://metwork-framework.org/pub/metwork/releases/rpms/release_1.0/portable/

**Comment by dearith** [comment]
Good news. Thanks!
