### ISSUE TITLE
no postgis in mfext rpms

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfext#109]
```
$ find /opt/metwork-mfext-master |grep postgis
/opt/metwork-mfext-master/opt/mapserver/include/mapserver/mappostgis.h
/opt/metwork-mfext-master/opt/scientific/share/metwork_packages/postgis.yaml
=> no postgis lib
```

and it breaks mfbase initialization

**Comment by thefab** [comment]
probably a packaging issue

we cache a layer directory after its build
and postgis add files after 

the first time is ok, but when we use the cache, not

we have to find another way

**Comment by thebaptiste** [comment]
This issue will be properly fixed (I hope !), even when the cache has been used to build, in next mfext rpm

**Comment by thefab** [comment]
fixed:

- in master by rebuilding everything after cache drop
- in integration by #110
