### ISSUE TITLE
.releaseignore / make release : incorrect exclusion with lines beginning with !

### ISSUE THREAD

**Issue by albator75** [metwork-framework/mfext#1178]
#HI !

Here's my case : 

`#want to ignore all in files/directory in a directory except one file/directory`
`/test/`
`!/test/toto`

According to gitignore definition (tested fine with git) these 2 lines should exclude everything in `test` directory except `toto` file.

Running `make release` results in nothing in the plugin, no file test/toto 

I think the problem is in `mfext/opt/python3/lib/python3.8/site-packages/mfplugin/plugin.py` when dealing with the `matches()` results in the os.walk() loop...
The `matches()` function seems to work fine (tested independently).

I will try to do some more tests.

links with : #1048

**Comment by thebaptiste** [comment]
Thanks @albator75 for your PR on mfplugin and sorry for the huge elapsed time since you did it.
