### ISSUE TITLE
Metwork 1.0 - Upgrade GDAL to the latest version

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfext#1230]
Is possible to upgrade GDAL version to the latest version, e.g. v 3.3.3 ?

Currently, GDAL version 3.0.2. This version doesn't handle `[nmi_i]` unit in GML. V 3.3.3 handles this unit : see https://github.com/OSGeo/gdal/issues/3118.

For example, create geometry from the following gml doesn't work with v 3.0.2 :
 ```
                                    <gml:polygonPatches>
                                                <gml:PolygonPatch interpolation="planar">
                                                    <gml:exterior>
                                                        <gml:Ring>
                                                            <gml:curveMember xlink:type="simple">
                                                                <gml:Curve gml:id="uuid.81b75d0b-a73f-465b-a86e-bd8842cb8941">
                                                                    <gml:segments>
                                                                        <gml:CircleByCenterPoint  srsName="urn:ogc:def:crs:EPSG::4326" interpolation="circularArcCenterPointWithRadius" numArc="1">
                                                                            <gml:pos>-10.8 121.9</gml:pos>
                                                                            <gml:radius uom="[nmi_i]">140.0</gml:radius>
                                                                        </gml:CircleByCenterPoint>
                                                                    </gml:segments>
                                                                </gml:Curve>
                                                            </gml:curveMember>
                                                        </gml:Ring>
                                                    </gml:exterior>
                                                </gml:PolygonPatch>
                                          </gml:polygonPatches>
```
The geometry create with ogr.CreateGeometryFromGML() python function is not correct, uom="[nmi_i]" not recognized by GML Reader, and it assumes uom is deg in this case.

It works with v3.3.3.

**Comment by dearith** [comment]
I think, proj package must be upgrade to avoid error like this : 
`proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation.`

**Comment by thebaptiste** [comment]
I will try to do it but : 
- not in a release 1.0.x or 1.1.y
- not in Metwork 1.2 either : for operational needs at Meteo-France, we are about to release Metwork 1.2 these days and gdal and proj are very significant dependencies of many other scientific packages, we must upgrade them very carefully.
So you will have to wait. Sorry about that.

**Comment by dearith** [comment]
Thanks for your comments. Yes, I understand it's not so easy tu upgrade gdal ad its depencencies.

Currently we use Metwork 1.0.x with Metgate SWIM.

I understand the gdal upgrade will be in a Metwork version > 1.2. 

So we will have to upgrade the Metwork version. Is there major difference between Metwork 1.0, 1.1, 1.2 ? How to upgrade from Metwork 1.0 to 1.1, 1.2 ? Just change the yum repo or do we need to unistall Metwork 1.0 and install Metwork 1.1 or 1.2

**Comment by thebaptiste** [comment]
There is no huge refactoring between Metwork 1.0 and Metwork 1.1 or Metwork 1.2, but many bug fixes, upgrades or new provided packages in mfext and addon_scientific mostly. Since last week you can find the complete changelogs of all releases in the master branch of each Metwork repository.
Among changes, Metwork 1.2 is in python 3.9.
For mfext and addons, multiple Metwork versions can be installed and used concurrently on the same machine. You just have to add the yum repositories and to select the loaded profile to use one version or another.
But for mfserv, mfdata, mfbase... two versions can't be running together. Or may be it's possible if you change the used ports (I have to check that).

**Comment by thebaptiste** [comment]
GDAL has not been upgraded either in Metwork 2.0 released last month.
But I have just upgraded GDAL to release 3.3.3 in the master branch (for the next stable release 2.1 or 3.0 planned for the end of the year).

Can you provide more details on your problem regarding PROJ, may be in another issue (I would like to close this one) ? I intend to upgrade at least to PROJ 7.

**Comment by thebaptiste** [comment]
For your information, the major change in Metword 2.0 is that it is built under rockylinux 8.5. So it can't be installed on centos 6 or 7.

**Comment by thebaptiste** [comment]
GDAL is now in 3.5.3 and PROJ in 9.0.1 in master branch and release 2.1.
I close this issue. Please open another one in case of other problems.
