### ISSUE TITLE
restore the .configuration_cache deletion during make clean

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1367]
The commit https://github.com/metwork-framework/mfext/commit/302bbf6eb5fffc53c3915c6784937699f02097d8 has been "cancelled" (by commit https://github.com/metwork-framework/mfext/commit/90615953365483218c358628c81af5021b9706a4) whereas it woud be a good idea to remove the pickle `.configuration_cache` at least during the `make clean` action.
I personally deleted it several times manually. Why ? -->
- if you install/load a **new mfext layer** in a metwork module, this layer is not taken into account into the PYTHONPATH of existing plugin, until you remove this `.configuration_cache` file and redo `make develop`
- if you **upgrade the metwork version** (from v1.2 to v2 for example), the new mfext-2.0 path is not taken into account into the PYTHONPATH of existing plugin, so it raises errors until you remove the `.configuration_cache` and redo `make develop`

Important: `.configuration_cache` file is declared in `.gitignore` and not commited.

**Comment by matthieumarrast** [comment]
related to #956

**Comment by thebaptiste** [comment]
Closed by https://github.com/metwork-framework/mfext/commit/ab0081555bd4c9e20822a6bd4ea6f38af6b376e0
