### ISSUE TITLE
Migration to NodeJS v16 (at least)

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1372]
Currently NodeJS v10.16.3 is provided by MetWork, which is no more supported. See https://nodejs.org/en/about/releases.
Can you please upgrade to at least version 16, better version 18.

**Comment by matthieumarrast** [comment]
thank you @thebaptiste , when will it be released ?

**Comment by thebaptiste** [comment]
With release 2.1 or 3.0 in a few months
