### ISSUE TITLE
Can't change hostname color in prompt

### ISSUE THREAD

**Issue by thebaptiste** [metwork-framework/mfext#1488]
I didn't succeed to change the hostname color in prompt (to prefer 'RED' for production host) using variables `LP_COLOR_*`

Maybe liquidprompt should be upgraded

**Comment by thebaptiste** [comment]
It seems that it's working with `.metwork.custom_profile`: 
```
export LP_HOSTNAME_ALWAYS=1
export LP_COLOR_HOST="\[$(tput setaf 1)\]"
```

Or `LP_COLOR_SSH` for a ssh connexion

Thanks to @matthieumarrast

**Comment by matthieumarrast** [comment]
you must add
`export LP_COLOR_SU="\[$(tput setaf 1)\]"`
if you execute `su - <module>` after being connected to your server using ssh
