### ISSUE TITLE
using cached wheels in plugin, and make clean

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1514]
In "dev_link" mode, after a `make clean` (which removes `python?_virtualenv_sources/src` and `local`) command on a plugin directory, the `make develop` command is still "Using cached" packages.

```
[mfserv:~/my_plugin]↥ develop ± make superclean
[mfserv:~/my_plugin]↥ develop ± make develop
- Checking plugin...                                       [ OK ]              
[DEBUG]: loading tempolayer7140[/home/mfserv/my_plugin/python3_virtualenv_sources/tempolayer7140]
Collecting django<4.0,>=3.2
  Using cached Django-3.2.16-py3-none-any.whl (7.9 MB)
```

- do you know why ?
- where are stored the cached wheels ? (I can't find them under `~/.cache/pip/...`)
- finaly, how to **not** use cached wheels ?

I ask these questions in order to try to find solutions for speeding up CI pipelines.

**Comment by thebaptiste** [comment]
The cached wheels seems to be "hidden" in binary files under `~/.cache/pip/http`
Remove this directory and you won't have messages about using cached wheels.
But why don't you want to use them ? Do you prefer to download them at each `make develop` ? I don't think it will speed up the CI...

**Comment by thebaptiste** [comment]
The cached wheels seems to be "hidden" in binary files under `~/.cache/pip/http`
Remove this directory and you won't have messages about using cached wheels.
But why don't you want to use them ? Do you prefer to download them at each `make develop` ? I don't think it will speed up the CI...

**Comment by matthieumarrast** [comment]
OK thank you for the answers.
