### ISSUE TITLE
~/.ssh folder not kept while upgrading metwork

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1518]
While upgrading metwork from v1.x to 2.x a new `/home/mfdata` folder has been created.
The old one has been saved to `/home/mfdata.rpmssave...`

Our sftp plugin failed because the ssh private key located before on `/home/mfdata/.ssh` has not been copied to the new home folder. It is still present in `/home/mfdata.rpmssave.../.ssh/`

Is it possible to copy/move the .ssh dir to the new home ?

**Comment by thebaptiste** [comment]
Closed by #1525
