### ISSUE TITLE
block_autorestart working only 10 minutes

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1528]
We are using flag file `${MFMODULE_RUNTIME_HOME}/var/block_autorestart` to block the module autorestart, after stopping it, while we are doing some updates.

But this flag is deleted after 10 minutes and the module restarts anyway.

Is there a reason in https://github.com/metwork-framework/mfext/blob/master/adm/templates/mfxxx.autorestart to delete it after 10 minutes, before checking its presence :
```
find "${MFMODULE_RUNTIME_HOME}/var/block_autorestart" -type f -mmin +10 -delete >/dev/null 2>&1
if test -f "${MFMODULE_RUNTIME_HOME}/var/block_autorestart"; then
    log INFO "found ${MFMODULE_RUNTIME_HOME}/var/block_autorestart => we do nothing"
    exit 0
fi
```

To bypass this issue, we are forced to execute this command to make the file immutable:
`chattr +i /home/mfserv/var/block_autorestart`

**Comment by thebaptiste** [comment]
Never heard of this file...
I think the idea is to be sure not to forget ro remove it !
If you are doing some updates taking more than 10 minutes (which is quite long), may be you should rather stop the module ?
Or may be this duration should be user configurable.

**Comment by thebaptiste** [comment]
For me this is not an issue but a feature

**Comment by matthieumarrast** [comment]
Indeed if module mfserv is stopped, the crontab is uninstalled so the autorestart is not executed in cron:
```
# Autorestart
*/5 * * * * /opt/metwork-mfext-2.1/bin/_no_automatic_kill.sh /opt/metwork-mfserv-2.1/bin/cronwrap.sh --lock --timeout=900 --log-capture-to=autorestart.log -- mfserv.autorestart
```
so the module is not restarted, even if block_autorestart is present or not.

Maybe the issue was present in v0.x or v1.x but in v2.x I do not reproduce it, I close this ticket.
