### ISSUE TITLE
.git folder not removed while releasing a plugin

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1549]
It is useless to deliver the **.git** folder in plugin artifact (see below screenshot).
I thought the `.git` in **.releaseignore** file must be fixed and prepend by a slash, as below:
```
/.git
```
But it's still not working. A problem with the **gitignore_parser** https://github.com/mherrmann/gitignore_parser ?

Involved files:
- https://github.com/metwork-framework/mfserv/blob/master/adm/templates/plugins/_common/releaseignore
- https://github.com/metwork-framework/mfdata/blob/master/adm/templates/plugins/_common/.releaseignore
- https://github.com/metwork-framework/mfbase/blob/master/adm/templates/plugins/default/%7B%7Bcookiecutter.name%7D%7D/.release_ignore

![image](https://user-images.githubusercontent.com/38913120/219088634-4bae2f4f-059b-467a-a013-dc646e13f80a.png)

**Comment by matthieumarrast** [comment]
It seems to be an impact of a recent modification : https://github.com/metwork-framework/mfplugin/commit/ef1a1343392fa1c08838b0e21355f432e00db4e6
As the folder deletion has been moved after the file deletion, and as we check than the folder is non-empty with `not os.listdir` (see below screen)
![image](https://user-images.githubusercontent.com/38913120/219102582-08fea906-ab62-44d2-9e52-7f91fd97dbee.png)
the ".git" folder cannot be removed. 

Because all the files inside this folder must **first** be deleted. 
Declaring `/.git/*` is also not working.

(Reminder: the goal of the above mentionned commit was to keep files declared like that: `!/.git/toto`)

=> Workaround:
```
/.git/**
.git*
```
 works !

**Comment by matthieumarrast** [comment]
Moreover in `.releaseignore` it is written:
```
# don't add python3_virtualenv_sources here as we need it for installing
# (it will be removed just after install)
```
but this folder `python3_virtualenv_sources` is present in the plugin file !!

**Comment by thebaptiste** [comment]
> It seems to be an impact of a recent modification : [metwork-framework/mfplugin@ef1a134](https://github.com/metwork-framework/mfplugin/commit/ef1a1343392fa1c08838b0e21355f432e00db4e6) As the folder deletion has been moved after the file deletion, and as we check than the folder is non-empty with `not os.listdir` (see below screen) ![image](https://user-images.githubusercontent.com/38913120/219102582-08fea906-ab62-44d2-9e52-7f91fd97dbee.png) the ".git" folder cannot be removed.
> 
> Because all the files inside this folder must **first** be deleted. Declaring `/.git/*` is also not working.
> 
> (Reminder: the goal of the above mentionned commit was to keep files declared like that: `!/.git/toto`)
> 
> => Workaround:
> 
> ```
> /.git/**
> .git*
> ```
> 
> works !

`/.git/` is not working ?

**Comment by thebaptiste** [comment]
> Moreover in `.releaseignore` it is written:
> 
> ```
> # don't add python3_virtualenv_sources here as we need it for installing
> # (it will be removed just after install)
> ```
> 
> but this folder `python3_virtualenv_sources` is present in the plugin file !!

This folder is mandatory in the plugin file. Install of the plugin file doesn't work without it.
Before metwork 1.0, it was removed (in `_plugins.postinstall`) after installation on the "installed plugin" on `${MFMODULE_RUNTIME_HOME}/var/plugins/<plugin_name>` (not in the plugin file)
It is not done anymore since metwork 1.0, probably because of the "develop" mode (risk of loss in the source directory ?).

So I think we just have to remove the second line of the comment : `# (it will be removed just after install)` and keep the first one

**Comment by matthieumarrast** [comment]
probably it means the folder `python3_virtualenv_sources` is removed on the `~/var/plugins/<plugin>` folder after installation, but not into the `.plugin` file

**Comment by matthieumarrast** [comment]
> 
> 
> `/.git/` is not working ?

yes indeed `/.git/` seems to works... 

way to reproduce :
```
bootstrap_plugin.py create foo --no-input
cd foo
# create a .git folder inside plugin
git init
make release
# check plugin content
tar -tf foo-0.0.1-1.metwork.mfserv.plugin
```

it seems also OK if we declare (after creation a `/.git/tokeep` file):
```
/.git/
!/.git/tokeep
```

so what do you think ?
we can push:
```
/.git/
.git*
```

**Comment by thebaptiste** [comment]
Closed by https://github.com/metwork-framework/mfserv/pull/581, https://github.com/metwork-framework/mfbase/pull/239 and https://github.com/metwork-framework/mfdata/pull/465
