### ISSUE TITLE
Simplify _metwork.spec with one rpm for each layer and self discovery of list of layers and dependencies

### ISSUE THREAD

**Issue by thebaptiste** [metwork-framework/mfext#160]
We want to simplify _metwork.spec updates (too many things are "hard-coded" each time we have to add a layer). We would like to have : 

- One elementary rpm for each layer with the name metwork-_module_-layer-_layer_-_branch_ (example : metwork-mfext-layer-scientific-integration)

- Self discovery of the list of layers of each module (using the list of directories on {{MODULE_HOME}}/opt/) to build the elementary rpm corresponding to each layer

- Self discovery of the dependencies for each elementary rpm (using .layerapi2_dependencies of the corresponding layer)

- The files or directories of the root layer of a module (which are not under {{MODULE_HOME}}/opt/root but directly under {{MODULE_HOME}} are in the rpm metwork-_module_-layer-root-_branch_ (example metwork-mfext-layer-root-integration with .layerapi2_label and directories bin, config, lib, include and share, ie "everything but opt"), with self discovery

- Hard-coded meta rpms installing the list of unitary rpms with backward compatibility with the names of the current rpms (this can't be self discovered)

**Comment by thefab** [comment]
:+1:
