### ISSUE TITLE
documentation - installation guide - bad rpm repository link

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1700]
If a user try to access to the documentation from the README.md in a module repository- exemple https://github.com/metwork-framework/mfserv, two links are provided:

- (for master (development) version), see [this dedicated site](http://metwork-framework.org/pub/metwork/continuous_integration/docs/master/mfserv/) for reference documentation.
- (for latest released stable version), see [this dedicated site](http://metwork-framework.org/pub/metwork/releases/docs/stable/mfserv/) for reference documentation.

Using the first link, page "installation guide", the rpm repository path which is given is http://metwork-framework.org/pub/metwork/releases/rpms/release_1.0/portable/, **this is not the last version (2.1)**
Using the second link, page "installation guide", the rpm repository path which is given is http://metwork-framework.org/pub/metwork/releases/rpms/stable/portable/, **this path does not exist !**

**Comment by thebaptiste** [comment]
The first link is almost normal. It's just an example with release_1.0. Of course we can replace 1.0 by last 2.1, but the aim is to indicate that each release has its own repository. I will replace 1.0 by 2.1 but with a comment to explicit the idea.

**Comment by thebaptiste** [comment]
Done
