### ISSUE TITLE
upgrade nodejs

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1719]
NodeJS version (v16.15.1) provided by MetWork is not updated for security support from 11 Sep 2023.
Cf. https://endoflife.date/nodejs

Upgrade to V20 (LTS)

**Comment by thebaptiste** [comment]
This upgrade to 20.0.0 is available on branch `experimental_nodejs20`
Could you check it brings no regression on : 

- [x] plugin templates node and node_noweb in mfserv
- [x] mfadmin (kibana and maybe ldap)

**Comment by matthieumarrast** [comment]
Testing procedure:

Image: **metwork/mfxxx-centos8-buildimage:integration**
Repo: `baseurl=http://metwork-framework.org/pub/metwork/continuous_integration/rpms/experimental_nodejs20/centos8/`
Installation:
- metwork-mfserv
- metwork-mfadmin
- metwork-mfext-layer-nodejs

```
[root@4c076daf21e9 /]# su - mfserv
Welcome on 4c076daf21e9 (4c076daf21e9, 172.17.0.2)
(module: MFSERV, version: experimental_nodejs20.ci940.42930f4)

 13:28:55 up 20 min,  0 users,  load average: 1.28, 1.70, 1.66
```
Check versions:
```
[mfserv@4c076daf21e9:~] $ node --version
v20.9.0
[mfserv@4c076daf21e9:~] $ npm --version
10.1.0
```
-----------------------------------------------------------------------------------------------------------
- test template **node** 
```
[mfserv@4c076daf21e9:~] $ bootstrap_plugin.py create --template node template_node
```
```
[mfserv@4c076daf21e9:~] $ cd template_node/
[mfserv@4c076daf21e9:~/template_node] $ make develop
- Checking plugin...                                       [ OK ]              

added 62 packages, and audited 63 packages in 4s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 10.1.0 -> 10.2.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.3
npm notice Run npm install -g npm@10.2.3 to update!
npm notice 
- Devlinking plugin template_node...                       [ OK ] 
```
```
[mfserv@4c076daf21e9:~/template_node] $ plugins.list
┌Installed plugins (1)─────┬──────────┬────────────────────────────────────────┐
│ Name          │ Version  │ Release  │ Home                                   │
├───────────────┼──────────┼──────────┼────────────────────────────────────────┤
│ template_node │ dev_link │ dev_link │ /home/mfserv/var/plugins/template_node │
└───────────────┴──────────┴──────────┴────────────────────────────────────────┘
```
```
[mfserv@4c076daf21e9:~/template_node] $ curl http://localhost:18868/template_node
Hello World from template_node!
```
-----------------------------------------------------------------------------------------------------------
- test template **node_noweb** 
```
[mfserv@4c076daf21e9:~] $ bootstrap_plugin.py create --template node_noweb template_node_noweb
[mfserv@4c076daf21e9:~] $ cd template_node_noweb/
[mfserv@4c076daf21e9:~/template_node_noweb] $ make develop
- Checking plugin...                                       [ OK ]              

up to date, audited 1 package in 214ms

found 0 vulnerabilities
plugin_wrapper "/home/mfserv/template_node_noweb" -- npm install

up to date, audited 1 package in 217ms

found 0 vulnerabilities
[mfserv@4c076daf21e9:~/template_node_noweb] 1 $ npm install express

added 62 packages, and audited 67 packages in 2s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
add hello world code on `app.js`, from https://www.npmjs.com/package/express
```
[mfserv@4c076daf21e9:~] $ curl http://localhost:3000
Hello World
```
-----------------------------------------------------------------------------------------------------------

Also tested **OK** with a own ReactJS plugin (npm + node).

-----------------------------------------------------------------------------------------------------------

For testing the LDAP part of mfadmin (the one using node) I need to be into an enterprise network.... I'll do it later.

**Comment by matthieumarrast** [comment]
There is no NodeJs on mfadmin, it was a confusion with an ASGI app (uvicorn/python/FastAPI) used for the LDAP connection.

**Comment by thebaptiste** [comment]
> There is no NodeJs on mfadmin, it was a confusion with an ASGI app (uvicorn/python/FastAPI) used for the LDAP connection.

There is an old nodejs version (10.24.1) inside kibana, the nodejs provided by mfext is not used.

**Comment by thebaptiste** [comment]
So I will merge the upgrade of NodeJs in mfext
