### ISSUE TITLE
Add thermofeel python library in mfext

### ISSUE THREAD

**Issue by elvismto** [metwork-framework/mfext#1953]
Hello,
Could you add this thermofeeel library in metwork please ?
https://thermofeel.readthedocs.io/en/latest/

Many thanks !

Elvis Renard

**Comment by thebaptiste** [comment]
Hello Elvis

Yes I can ! I'm on it...

**Comment by elvismto** [comment]
Hello !
Great ! Thank you !

**Comment by thebaptiste** [comment]
It's done (master branch)
