### ISSUE TITLE
Upgrade GEOS library to latest version (3.7.1)

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfext#204]
It would be nice, if possible to upgrage GEOS to 3.7.1 in order to check if this release fix a bug when using spatial filters in a WFS request:

Error message is: python: geos_ts_c.cpp:405: void GEOSFree_r(GEOSContextHandle_t, void*): Assertion `0 != extHandle' failed.

The filter used is : <Filter><Intersects><PropertyName>wkb_geometry</PropertyName><gml:Polygon><gml:outerBoundaryIs><gml:LinearRing><gml:coordinates>71.980000,-17.600000%2070.980000,-23.600000%2072.000000,-17.500000%2071.980000,-17.600000</gml:coordinates></gml:LinearRing></gml:outerBoundaryIs></gml:Polygon></Intersects></Filter>

Thanks

**Comment by thebaptiste** [comment]
Done and ready to merge in master
