### ISSUE TITLE
Define meta packages "scientific" and "python2" somewhere

### ISSUE THREAD

**Issue by thebaptiste** [metwork-framework/mfext#283]
Since the split of mfext scientific layers between scientific_core layer in mfext and other layers in mfextaddon_scientific, these 2 meta packages are no longer defined.

**Comment by thefab** [comment]
we have to fix this before 0.7 release or fix the corresponding documentation

**Comment by thebaptiste** [comment]
We have decided to suppress these meta packages and to fix the corresponding documentation.
Each single layer rpm from a branch now provides an alias without the branch name, so the branch name is not necessary to install the layers corresponding to the old meta packages.
