### ISSUE TITLE
Compilation of 0500_openjdk failed

### ISSUE THREAD

**Issue by lemcp** [metwork-framework/mfext#315]
hi,

i have try to compile mfext and the download of openjdk failed with this error 

Trying to download https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz...
--2019-04-27 01:53:22--  https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz
Resolving download.java.net (download.java.net)... 23.48.91.197
Connecting to download.java.net (download.java.net)|23.48.91.197|:443... connected.
The certificate's owner does not match hostname ‘download.java.net’
HTTP request sent, awaiting response... 403 Forbidden
2019-04-27 01:53:23 ERROR 403: Forbidden.

Can you advise me on a new URL? and update version 0.6 of mfext?

thank you in advance

**Comment by thefab** [comment]
Same problem for me. It’s really new.

**Comment by lemcp** [comment]
for information this file is on this site : https://controlssoftware.sns.ornl.gov/css_phoebus/nightly/
why not build a directory of internal sources?

**Comment by thefab** [comment]
merged in `integration` branch, it will be probably in `master` tomorrow and backported to `release_0.6`

**Comment by thefab** [comment]
And to answer your question, we can point to several servers in `sources` file of each component.

But, when we have too many problems with some of these mirrors, we upload the file on this repository : https://github.com/metwork-framework/external_sources (and add the corresponding link to the `sources`file).

Feel free to propose a PR about this if you want ;-)
