### ISSUE TITLE
move python2 stuff in a dedicated addon

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfext#412]

**Comment by thebaptiste** [comment]
Done. Pull requests to be merged after 0.10 : 
https://github.com/metwork-framework/resources/pull/58
https://github.com/metwork-framework/mfext/pull/760
https://github.com/metwork-framework/mfextaddon_python2/pull/19
https://github.com/metwork-framework/mfextaddon_scientific/pull/103
https://github.com/metwork-framework/mfserv/pull/330
https://github.com/metwork-framework/mfdata/pull/268
https://github.com/metwork-framework/mfextaddons/pull/3
