### ISSUE TITLE
block core dump in metwork profiles

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfext#515]
* soft core 0
* hard core 0

?

**Comment by thefab** [comment]
it should be probably better in profile

**Comment by thefab** [comment]
and it would be better to have an option to avoid this (in some cases)

**Comment by thebaptiste** [comment]
Does the option should be driven by an environment variable in a custom profile ?

If we put `ulimit -c 0` in a standard metwork profile, we won't be able to increase the limit in a custom profile loaded after (we always can decrease such limits but we never can increase them).
May be we could load an optional dedicated custom profile before loading the standard metwork profiles and forbid coredumps only if this dedicated profile has not allowed them ?

Or may be simpler : use an optional dedicated file `.coredump_allowed` to allow coredumps (coredumps are forbidden unless this file exists or something like that).

**Comment by thebaptiste** [comment]
@thefab : do you have an opinion ?

**Comment by thefab** [comment]
Maybe a standard configuration option in module `config.ini` ?
