### ISSUE TITLE
Add possibility to install pypi modules with SCLs

### ISSUE THREAD

**Issue by thebaptiste** [metwork-framework/mfext#584]
Explanation with an example : 
- gdal is now built in scientific_core@mfext with SCLs (because we need a recent gcc compiler)
- when we pip install the corresponding pypi modules GDAL in python2_scientific@mfext or python3_scientific@mfext, a compilation with gcc is necessary, and if fails if we don't do it with the same compiler used to build gdal in scientific_core@mfext

**Comment by thebaptiste** [comment]
We can do it by adding specific makefiles for this use. In these makefiles, the scl devtoolset-7 is enabled.

Note : may be the scl devtoolset-7 should be enabled by default for all compilations in Metwork in order to always use a recent compiler to build.

**Comment by thefab** [comment]
> Note : may be the scl devtoolset-7 should be enabled by default for all compilations in Metwork in order to always use a recent compiler to build.

Interesting question. It sounds a good idea but I'm not sure about difficulties doing that. 

Good candidate for a dedicated experimental branch about that!

**Comment by thebaptiste** [comment]
We would need to use devtoolset-8 because : 
* centos6 : `gcc --version` : 4.4.7
* centos7 : `gcc --version` : 4.8.5
* devtoolset-7 : `gcc --version` : 7.3.1
* centos8 : `gcc --version` : 8.2.1
* devtoolset-8 : `gcc --version` : 8.3.1
