### ISSUE TITLE
Drop layer9_pythonX_misc layers

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfext#638]
Latest step of the `mfcom` migration/drop:

- [x] drop of `layer9_python3_misc`
    - [x] deal with `mfutil`
        - [x] remove `deprecated.py`
        - [x] release `mfutil` as a dedicated repository
        - [x] install this package in `python3` layer 
    - [x] migrate `circus_hooks` in a simple file in `mfext/adm`
        - [x] change corresponding calls (package name)
    - [x] migrate `conf_monitor` in a simple file in `mfext/adm`
        - [x] change corresponding calls (package name)
    - [x] migrate ` jsonlog2elasticsearch_metwork_addon` in a simple file in `mfext/adm` (work done in #644, metwork-framework/mfadmin#128 and #645)
        - [x] change corresponding calls (package name)
    - [x] migrate `mflog_addon` in a simple file in `mfext/adm`
        - [x] change corresponding calls (package name)
    - [x] drop any dependency on this layer in other layers/modules
        - [x] mfext
        - [x] mfsysmon
        - [x] mfadmin
        - [x] mfbase
        - [x] mfserv
        - [x] mfdata

- [x] drop of `layer9_python2_misc`
    - [x] deal with `mflog_addon` (see python3)
    - [x] deal with `mfutil` (see python3)
    - [x] drop any dependency on this layer in other layers/modules (see python3)

- [x] fix `bootstrap_plugin.py` or `mfutil` (`get_bash_output_or_die` has been removed from mfutil but is used in bootstrap_plugin.py)

**Comment by thebaptiste** [comment]
Done
