### ISSUE TITLE
python3 access

### ISSUE THREAD

**Issue by moas** [metwork-framework/mfext#688]
Hi,

I use docker as a development environment and would like to have a symbolic python3 link to the python3 installed via mfext. I need it for the configuration of my IDE (Pycharm).
Thanks!

**Comment by thefab** [comment]
I'm not sure to understand exactly what you need because:

```
[mfserv@xxxxx:~] $ which python3
/opt/metwork-mfext-master/opt/python3_core/bin/python3
[mfserv@xxxx:~] $ ll /opt/metwork-mfext-master/opt/python3_core/bin/python3
lrwxrwxrwx 1 root root 9 Jan 27 16:33 /opt/metwork-mfext-master/opt/python3_core/bin/python3 -> python3.7
```

So `/opt/metwork-mfext/opt/python3_core/bin/python3` is already the link you search?

**Comment by moas** [comment]
Thanks for your reply.
I fixed my problem. I set password to user mfdata and I use mfdata account to run remote connection and It more better
