### ISSUE TITLE
_make_crontab.sh : add MFSERV_CURRENT_PLUGIN_NAME to the parameters

### ISSUE THREAD

**Issue by ghost** [metwork-framework/mfext#748]
imo it would be more convenient, especially to re-use modules

**Comment by thefab** [comment]
good idea!

**Comment by thefab** [comment]
todo:
- [x] corresponding mfext changes
- [ ] mfserv/mfdata/mfbase examples (in templates) or dedicated ocumentation

**Comment by ghost** [comment]
et merci !
