### ISSUE TITLE
Add Postgresql Driver in GDAL (OGR2OGR)

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfext#76]
It would nice (and needful)  to include Postgresql driver in GDAL OGR2OGR.

Currently, Postgresql driver is missing in ogr2ogr installed by metwork (run ogrinfo --formats)

Thanks.

**Comment by thefab** [comment]
@thebaptiste we must talk over that because it's not easy to do because of layers order (gdal is built before postgresql and I think that postgis needs gdal also ?)

**Comment by thefab** [comment]
After talking with @thebaptiste  and @dearith, the idea would be:

- rename `layer2_postgresql` into `layer1_postgresql` (to be built before `layer1_scientific` (`gdal` is inside)
- move `postgis` out of `layer2_postgresql` into a new dedicated layer `layer2_postgis`
- fix layers dependencies in `mfbase` and `layer3_mapserver` to depend on `postgis` layer and not `postgresql`
- add `postgresql` support in `gdal`

**Comment by thebaptiste** [comment]
Done (when merged in master)
We don't need a specific layer for postgis which has been moved to scientific layer (layer1_scientific)

**Comment by thefab** [comment]
@thebaptiste : it seems to compile :-) an integration test would be great (in another PR)

maybe by parsing the output of `ogrinfo --formats |grep ...` like @dearith originaly suggested

**Comment by thebaptiste** [comment]
My commit add this format (output of 'ogrinfo --formats'): 
"PostgreSQL -vector- (rw+): PostgreSQL/PostGIS". 
And ogr2ogr is now linking with postgresql lib libpq.so.
I hope this will do the job. If not, please let us know.
I will add an integration test later.

**Comment by dearith** [comment]
Yes, this does the job.
Now, I was able to insert data into Postgresql with OGR2OGR delivered with MFEXT.
Thanks.
