### ISSUE TITLE
Upgrade coverage to the latest version (5.1)

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfext#788]
Hi,

It would be nice to have in Metwork the latest coverage python library.

Latest version is 5.1. It includes [new features ](https://coverage.readthedocs.io/en/coverage-5.1/whatsnew5x.html#new-features) we are interested in.

Thanks.

**Comment by thebaptiste** [comment]
Are you interested in 5.1 features or only 5.0 features ?
I'm asking because we are already in version 5.0.2 in master branch (so also in next Metwork version without any change).

**Comment by thebaptiste** [comment]
Of course we will anyway upgrade to version >=5.1 someday...

**Comment by dearith** [comment]
> Are you interested in 5.1 features or only 5.0 features ?
> I'm asking because we are already in version 5.0.2 in master branch (so also in next Metwork version without any change).

We are interested in at least 5.0 features.

Currently, we use the latest Metwork stable release (V 0.9.x), it seems coverage version is still 4.5.4 

```
coverage --version
Coverage.py, version 4.5.4 with C extension
Documentation at https://coverage.readthedocs.io
```
```
which coverage

/opt/metwork-mfext-0.9/opt/python3_devtools/bin/coverage
```

**Comment by thebaptiste** [comment]
As I said master branch (meaning "next stable release", i.e. Metwork 1.0) has coverage 5.0.2.
So I think we don't have to do anything to answer your need. If there are new features in coverage 5.1 you are interested in, please let us know.

**Comment by dearith** [comment]
Yes, but what about to have coverage 5.0.x or 5.1.x in Metwork 0.9.x ? Is it possible or not ?

Actually, it is not planned to use Metwork 1.0 in our project.

**Comment by thefab** [comment]
coverage >= 5.0 is a big change from coverage 4.9 (with plenty of breaking changes)
so it's a no-go for "metwork 0.9.x"

metwork 1.0 beta is going to be available next week with coverage 5.0.x and metwork 1.0 final will probably have coverage 5.1.x (or better)

**Comment by dearith** [comment]
Ok. We will use coverage 4.5.4 with Metwork 0.9. It is not a important issue on our side.

**Comment by thebaptiste** [comment]
Done in integration branch (version 5.1), waiting merge
