### ISSUE TITLE
add opencv-contrib-python-headless to the python3/scientific layer

### ISSUE THREAD

**Issue by OrangeJuce82** [metwork-framework/mfext#799]
Hi metwork team.

Would it be possible to add the library [opencv-contrib-python-headless](https://github.com/skvark/opencv-python) to the scientific layer ?

We need opencv in many MFDATA plugins.

Thx for your help and your precious time.

**Comment by thefab** [comment]
note: available with pip

**Comment by thebaptiste** [comment]
Done (waiting for merge)

**Comment by thebaptiste** [comment]
I hope it will work for your usage. We have only checked that `import cv2` succeeds (python3).

**Comment by OrangeJuce82** [comment]
Thx for your help.
