### ISSUE TITLE
Adding python testing packages

### ISSUE THREAD

**Issue by matdeslandes** [metwork-framework/mfext#803]
Hi,

Please, could you consider adding some pytest plugins for python3:
* [pytest-xdist](https://github.com/pytest-dev/pytest-xdist)
* [pytest-mock](https://github.com/pytest-dev)

Unrelated to pytest, but [freezegun](https://github.com/spulec/freezegun) to allow datetime testing.

Thanks,

**Comment by thebaptiste** [comment]
Done in integration branch, waiting merge
