### ISSUE TITLE
python3_devtools not in the PYTHONPATH under plugin_env

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfext#956]
I 'm running `coverage ` under the plugin_env of my plugin.

`coverage ` failed because paths to /python3_devtools/... are missing under plugin_env.

My test failed also because python3_scientific are missing.

out of plugin_env, it's OK : e.g.:
```
coverage --version

Coverage.py, version 5.1 with C extension
Full documentation is at https://coverage.readthedocs.io
```

under plugin_env, e.g. : 
```
coverage --version

Traceback (most recent call last):
  File "/opt/metwork-mfext-1.0/opt/python3_devtools/bin/coverage", line 7, in <module>
    from coverage.cmdline import main
ModuleNotFoundError: No module named 'coverage'
```

**PYTHONPATH content out of plugin_env** : 

```
***** PYTHONPATH *****

- /opt/metwork-mfext-1.0/opt/python3_scientific_core/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_scientific_core/lib
- /opt/metwork-mfext-1.0/opt/java/lib
- /opt/metwork-mfext-1.0/opt/monitoring/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/monitoring/lib
- /opt/metwork-mfext-1.0/opt/python3_devtools/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_devtools/lib
- /opt/metwork-mfext-1.0/opt/python3_mapserverapi/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_mapserverapi/lib
- /opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_scientific/lib
- /opt/metwork-mfext-1.0/opt/scientific/lib
- /opt/metwork-mfext-1.0/opt/scientific_system_libraries/lib
- /opt/metwork-mfext-1.0/opt/mapserver/lib
- /opt/metwork-mfext-1.0/opt/scientific_core/lib
- /opt/metwork-mfext-1.0/opt/devtools/lib
- /opt/metwork-mfext-1.0/opt/python3/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3/lib
- /opt/metwork-mfext-1.0/opt/tcltk/lib
- /opt/metwork-mfext-1.0/opt/python3_core/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_core/lib
- /opt/metwork-mfserv-1.0/lib
- /opt/metwork-mfext-1.0/opt/core/lib
- /opt/metwork-mfext-1.0/lib
```

**PYTHONPATH content under plugin_env** : 

```
***** PYTHONPATH *****

- /home/dearith10/metwork/mfserv/var/plugins/parsing_url/local/lib/python3.7/site-packages
- /home/dearith10/metwork/mfserv/var/plugins/parsing_url/local/lib
- /home/dearith10/metwork/mfserv/var/plugins/parsing_url/lib
- /home/dearith10/metgateswim/mfserv/parsing_url
- /opt/metwork-mfext-1.0/opt/python3_scientific_core/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_scientific_core/lib
- /opt/metwork-mfext-1.0/opt/java/lib
- /opt/metwork-mfext-1.0/opt/monitoring/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/monitoring/lib
- /opt/metwork-mfext-1.0/opt/python3_mapserverapi/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_mapserverapi/lib
- /opt/metwork-mfext-1.0/opt/mapserver/lib
- /opt/metwork-mfext-1.0/opt/scientific_core/lib
- /opt/metwork-mfext-1.0/opt/devtools/lib
- /opt/metwork-mfext-1.0/opt/python3/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3/lib
- /opt/metwork-mfext-1.0/opt/python3_core/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_core/lib
- /opt/metwork-mfserv-1.0/lib
- /opt/metwork-mfext-1.0/opt/core/lib
- /opt/metwork-mfext-1.0/lib
```

The difference is that : 
```
- /opt/metwork-mfext-1.0/opt/python3_devtools/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_devtools/lib

- /opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_scientific/lib
```
are missing under plugin_env

So the workaround I apply is to add theses paths under plugin_env before running coverage: 

` PYTHONPATH=${PYTHONPATH}:/opt/metwork-mfext-1.0/opt/python3_devtools/lib/python3.7/site-packages:/opt/metwork-mfext-1.0/opt/python3_devtools/lib:/opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages
:/opt/metwork-mfext-1.0/opt/python3_scientific/lib`

**Comment by dearith** [comment]
For your information, same issue on python3_devtools in Metwork 0.x

About python3_scientific, only in Metwork 1.0, perhaps because in Metwork 1.0 python3_scientific has been split into python3_scientific_core and python3_scientific.

**Comment by thefab** [comment]
not sure to understand

can you provide:

- the content of the `.layerapi2_dependencies` of your plugin
- the content of the `python3_virtualenv_sources/requirements3.txt` of your plugin (if any)

thanks

**Comment by dearith** [comment]
@thefab 

content of the `.layerapi2_dependencies` 
```
root@mfserv
python3@mfext
python3_scientific@mfext
```

content of `python3_virtualenv_sources/requirements3.txt`
```
# python3 requirements.txt file
# see https://pip.readthedocs.io/en/1.1/requirements.html
multidict==4.7.6
xmltodict==0.12.0
```

Note that : 

- I don't want to add python3_devtools in my `.layerapi2_dependencies`  and `python3_virtualenv_sources/requirements3.txt` (in order to have coverage in the plugin_env), because I don't want to have these dependencies in production environnement. 

- I use lxml in my plugin, I don't add lxml in the `python3_virtualenv_sources/requirements3.txt`, because lxml is in python3_scientific@mfext layer, and python3_scientific@mfext is not in PYTHONPATH under plugin_env. Note if I add lxml in the requirements.txt : either the version is same as Metwork, : OK, if the version is not the same, the version is installed by pip. So, I prefer not to add it to requirements .txt to be sure to use the lxml version provided by MetWork

Perhaps the 2 issues are distinct issues, 

- the first one with coverage and python3_devtools (I understand the fact that python3_devtools is not available under plugin_env, and I can try to run coverage with my unit tests by user layer_wrapper or something like that

- the second one, python3_scientific@mfext is really missing under plugin_evn. To be sure not to make a mistake, I uninstall my plugin, restart mfserv the reinstall my plugin (make supreclean, make develop), but python3_scientific@mfext is already missing in the PYTHONPATH

**Comment by dearith** [comment]
@thefab I forgot to mention that before running coverage under plugin_env, I load python3_devtools with `layer_load python3_devtools@mfext`

**Comment by dearith** [comment]
@thefab You can consider I don't do things in a right way.
I tried another way that works to run coverage for my_plugin : e.g. out of plugin_env, I run :

`layer_wrapper --layers=python3_devtools@mfext,my_plugin@mfserv -- coverage run -m unittest test/test_suite.py`

But, in another way, if my `.layerapi2_dependencies` files contains `python3_scientific@mfext`, when I run `plugin_env`, `python3_scientific@mfext` should be in the `PYTHONPATH`, no? (I run `metwork_debug `to check paths)

**Comment by thebaptiste** [comment]
I have reproduced the issue. @thefab you can reproduce it doing in a mfserv session : 
- bootstrap a new plugin
- change `.layerapi2_dependencies` of this plugin
`root@mfserv`
`python3@mfext`
`-python3_scientific@mfext`
- unload (if loaded) `python3_scientific@mfext`
- run `plugin_env`
- `python3_scientific@mfext` is loaded but PYTHONPATH does not include path to the corresponding python libraries

The problem occurs whether the plugin is installed or not
If you unload then reload `python3_scientific@mfext`, the libraries are now included in PYTHONPATH

**Comment by thebaptiste** [comment]
The problem seems to be in `plugin_wrapper.py` from `mfplugin` python library
PYTHONPATH seems to be kept as it was before calling `plugin_env` regardless of the dependencies

**Comment by thebaptiste** [comment]
@dearith : Waiting a fix from @thefab, unloading then reloading `python3_scientific@mfext` seems to be a workaround, but you will have to set this layer as optional in `.layerapi2_dependencies` (`-python3_scientific@mfext` instead of `python3_scientific@mfext` in this file, don't miss the "-" character) if you do not want to unload the layer corresponding to your plugin (`plugin_parsing_url@mfserv`) when unloading `python3_scientific@mfext`.
You can do the same for `python3_devtools@mfext` : if this layer is optional and not installed in production environment, your plugin will work anyway.

**Comment by dearith** [comment]
@thebaptiste Thanks. I'm waiting for the fix. It's not a blocking issue since there is a workaround.
For `python3_devtools@mfext`, I found a more suitable solution to run coverage with layer_wrapper as mentionned in my previous comment.

**Comment by thefab** [comment]
@thebaptiste: trying to reproduce this but:

```
# as mfserv
bootstrap_plugin.py create foobar
[...]

# changing foobar/.layerapi2_dependencies in
python3@mfext
root@mfserv
-python3_devtools@mfext

plugin_env

# check if python3_devtools is installed (yes)
layers --loaded-filter=yes |grep devtools
- (*) devtools@mfext [/home/fab/metwork/mfext/build/opt/devtools]
- (*) python3_devtools@mfext [/home/fab/metwork/mfext/build/opt/python3_devtools]

# check PYTHONPATH (it seems ok?)
echo ${PYTHONPATH} |sed 's/:/\n/g' |grep devtools
/home/fab/metwork/mfext/build/opt/python3_devtools/lib/python3.7/site-packages
/home/fab/metwork/mfext/build/opt/python3_devtools/lib
/home/fab/metwork/mfext/build/opt/devtools/lib
```

@thebaptiste do I miss something?

**Comment by dearith** [comment]
@thefab @thebaptiste 

In the meantime, I updated Metwork 1.0 (last rpms 2020-11-03). I'm trying again, and it works, either for `python3_devtools` or `python3_scientific`
Probably something has been fixed in this version.

**Comment by thebaptiste** [comment]
@thefab : Yes, you miss something : the problem occurs only if the considered layer (python3_devtools@mfext in your case) is not loaded before running plugin_env.

**Comment by thefab** [comment]
@thebaptiste: still can't reproduce

(foobar is not installed mfserv plugin)

```
$ cat foobar/.layerapi2_dependencies
python3@mfext
root@mfserv
-python3_devtools@mfext

$ layers |grep devtools
- (*) devtools@mfext [/home/fab/metwork/mfext/build/opt/devtools]
- python3_devtools@mfext [/home/fab/metwork/mfext/build/opt/python3_devtools]
$ # => python3_devtools is not loaded

$ env |grep PYTHONPATH |sed 's/:/\n/g' |grep devtools
/home/fab/metwork/mfext/build/opt/devtools/lib
$ # no python3_devtools in the PYTHONPATH

$ cd foobar
$ plugin_env

$ layers |grep devtools
- (*) devtools@mfext [/home/fab/metwork/mfext/build/opt/devtools]
- (*) python3_devtools@mfext [/home/fab/metwork/mfext/build/opt/python3_devtools]
$ # => loaded

$ env |grep PYTHONPATH |sed 's/:/\n/g' |grep devtools
/home/fab/metwork/mfext/build/opt/python3_devtools/lib/python3.7/site-packages
/home/fab/metwork/mfext/build/opt/python3_devtools/lib
/home/fab/metwork/mfext/build/opt/devtools/lib
$ # python3_devtools in the PYTHONPATH
```

**Comment by dearith** [comment]
@thefab 
As I said previously, since I have update Metwork 1.0 (last rpms 2020-11-03), it works. I can't no longer reproduce the issue. Perhaps this issue can be closed.

**Comment by thebaptiste** [comment]
If I'm the only one to reproduce it and if it's ok for both of you, let's forget. There is probably something wrong in my dev environment.

**Comment by thebaptiste** [comment]
Sorry but I reproduce it in a fresh docker session with last 1.0 rpms
May be it depends on the plugin type ? I used python3_flask.
```
layers
- plugin_welcome@mfserv [/home/mfserv/var/plugins/welcome]
- nodejs@mfserv [/opt/metwork-mfserv-1.0/opt/nodejs]
- (*) default@mfserv [/opt/metwork-mfserv-1.0/opt/default]
- (*) root@mfserv [/opt/metwork-mfserv-1.0]
- (*) monitoring@mfext [/opt/metwork-mfext-1.0/opt/monitoring]
- (*) nodejs@mfext [/opt/metwork-mfext-1.0/opt/nodejs]
- (*) openresty@mfext [/opt/metwork-mfext-1.0/opt/openresty]
- (*) core@mfext [/opt/metwork-mfext-1.0/opt/core]
- (*) python3_devtools@mfext [/opt/metwork-mfext-1.0/opt/python3_devtools]
- (*) python3@mfext [/opt/metwork-mfext-1.0/opt/python3]
- (*) tcltk@mfext [/opt/metwork-mfext-1.0/opt/tcltk]
- (*) default@mfext [/opt/metwork-mfext-1.0/opt/default]
- (*) devtools@mfext [/opt/metwork-mfext-1.0/opt/devtools]
- (*) python3_scientific_core@mfext [/opt/metwork-mfext-1.0/opt/python3_scientific_core]
- (*) java@mfext [/opt/metwork-mfext-1.0/opt/java]
- python3_circus@mfext [/opt/metwork-mfext-1.0/opt/python3_circus]
- (*) scientific_core@mfext [/opt/metwork-mfext-1.0/opt/scientific_core]
- (*) python3_core@mfext [/opt/metwork-mfext-1.0/opt/python3_core]
- (*) root@mfext [/opt/metwork-mfext-1.0]
echo ${PYTHONPATH} |sed 's/:/\n/g' |grep devtools
/opt/metwork-mfext-1.0/opt/devtools/lib
```

**Comment by thebaptiste** [comment]
with `baseurl=http://metwork-framework.org/pub/metwork/continuous_integration/rpms/release_1.0/centos6/`

**Comment by dearith** [comment]
With baseurl=http://metwork-framework.org/pub/metwork/releases/rpms/release_1.0/portable.

I create a new python3 flask plugin, it seems there is no issue.

```
 layers
- plugin_welcome@mfserv [/home/dearith10/metwork/mfserv/var/plugins/welcome]
- plugin_access_control@mfserv [/home/dearith10/metwork/mfserv/var/plugins/access_control]
- plugin_broker_capabilities@mfserv [/home/dearith10/metwork/mfserv/var/plugins/broker_capabilities]
- plugin_broker_model@mfserv [/home/dearith10/metwork/mfserv/var/plugins/broker_model]
- plugin_broker_service@mfserv [/home/dearith10/metwork/mfserv/var/plugins/broker_service]
- plugin_parsing_url@mfserv [/home/dearith10/metwork/mfserv/var/plugins/parsing_url]
- plugin_service_subscription@mfserv [/home/dearith10/metwork/mfserv/var/plugins/service_subscription]
- (*) default@mfserv [/opt/metwork-mfserv-1.0/opt/default]
- (*) root@mfserv [/opt/metwork-mfserv-1.0]
- (*) core@mfext [/opt/metwork-mfext-1.0/opt/core]
- (*) default@mfext [/opt/metwork-mfext-1.0/opt/default]
- (*) python3@mfext [/opt/metwork-mfext-1.0/opt/python3]
- python3_circus@mfext [/opt/metwork-mfext-1.0/opt/python3_circus]
- (*) python3_core@mfext [/opt/metwork-mfext-1.0/opt/python3_core]
- (*) openresty@mfext [/opt/metwork-mfext-1.0/opt/openresty]
- (*) monitoring@mfext [/opt/metwork-mfext-1.0/opt/monitoring]
- (*) devtools@mfext [/opt/metwork-mfext-1.0/opt/devtools]
- (*) scientific_core@mfext [/opt/metwork-mfext-1.0/opt/scientific_core]
- (*) mapserver@mfext [/opt/metwork-mfext-1.0/opt/mapserver]
- (*) python3_mapserverapi@mfext [/opt/metwork-mfext-1.0/opt/python3_mapserverapi]
- (*) python3_scientific_core@mfext [/opt/metwork-mfext-1.0/opt/python3_scientific_core]
- (*) java@mfext [/opt/metwork-mfext-1.0/opt/java]
- (*) python3_devtools@mfext [/opt/metwork-mfext-1.0/opt/python3_devtools]
- (*) scientific_system_libraries@mfext [/opt/metwork-mfext-1.0/opt/scientific_system_libraries]
- (*) scientific@mfext [/opt/metwork-mfext-1.0/opt/scientific]
- (*) tcltk@mfext [/opt/metwork-mfext-1.0/opt/tcltk]
- (*) python3_scientific@mfext [/opt/metwork-mfext-1.0/opt/python3_scientific]
- (*) nodejs@mfext [/opt/metwork-mfext-1.0/opt/nodejs]
- (*) root@mfext [/opt/metwork-mfext-1.0]
```
```
echo ${PYTHONPATH} |sed 's/:/\n/g' |grep devtools

/opt/metwork-mfext-1.0/opt/python3_devtools/lib/python3.7/site-packages
/opt/metwork-mfext-1.0/opt/python3_devtools/lib
/opt/metwork-mfext-1.0/opt/devtools/lib
```
**under plugin_env:**

```
metwork_debug
***** PYTHONPATH *****

- /home/dearith10/metgateswim/mfserv/foo_flask10b
- /opt/metwork-mfext-1.0/opt/python3_scientific_core/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_scientific_core/lib
- /opt/metwork-mfext-1.0/opt/nodejs/lib
- /opt/metwork-mfext-1.0/opt/java/lib
- /opt/metwork-mfext-1.0/opt/monitoring/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/monitoring/lib
- /opt/metwork-mfext-1.0/opt/python3_devtools/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_devtools/lib
- /opt/metwork-mfext-1.0/opt/python3_mapserverapi/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_mapserverapi/lib
- /opt/metwork-mfext-1.0/opt/python3_scientific/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_scientific/lib
- /opt/metwork-mfext-1.0/opt/scientific/lib
- /opt/metwork-mfext-1.0/opt/scientific_system_libraries/lib
- /opt/metwork-mfext-1.0/opt/mapserver/lib
- /opt/metwork-mfext-1.0/opt/scientific_core/lib
- /opt/metwork-mfext-1.0/opt/devtools/lib
- /opt/metwork-mfext-1.0/opt/python3/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3/lib
- /opt/metwork-mfext-1.0/opt/tcltk/lib
- /opt/metwork-mfext-1.0/opt/python3_core/lib/python3.7/site-packages
- /opt/metwork-mfext-1.0/opt/python3_core/lib
- /opt/metwork-mfserv-1.0/lib
- /opt/metwork-mfext-1.0/opt/core/lib
- /opt/metwork-mfext-1.0/lib
```

```
echo ${PYTHONPATH} |sed 's/:/\n/g' |grep devtools

/opt/metwork-mfext-1.0/opt/python3_devtools/lib/python3.7/site-packages
/opt/metwork-mfext-1.0/opt/python3_devtools/lib
/opt/metwork-mfext-1.0/opt/devtools/lib
```

**Comment by thebaptiste** [comment]
What I did on metwork-framework.org (@thefab : try to reproduce exactly)
`docker run -it metwork/mfxxx-centos6-buildimage:release_1.0 bash`
Then
`yum install metwork-mfserv-full`
`service metwork start`
Then
`su - mfserv`
 `layer_unload python3_devtools@mfext`
`bootstrap_plugin.py create --template=python3_flask my_plugin`
`cd my_plugin`
Change .layerapi2_dependencies (it's probably not necessary) then
`plugin_env`
`layers | grep devtools`
`echo ${PYTHONPATH} |sed 's/:/\n/g' |grep devtools`

**Comment by thebaptiste** [comment]
@dearith : Did you try to unload python3_devtools@mfext **before** running plugin_env ?

**Comment by dearith** [comment]
@thebaptiste 
Yes you are right, if you unload `python3_devtools@mfext` **before** `bootstrap_plugin.py create` , then `plugin_env` : `python3_devtools@mfext` is not in the `PYTHONPATH `:
```
echo ${PYTHONPATH} |sed 's/:/\n/g' |grep devtools
/opt/metwork-mfext-1.0/opt/devtools/lib
```

**Comment by matthieumarrast** [comment]
Issue reproduced today on Metwork 1.2, with layer `python3_scientific` :
```
[mfdata:~] $ is_layer_loaded python3_scientific@mfext
1
[mfdata:~] $ bootstrap_plugin.py create test_plugin
[mfdata:~] $ cd test_plugin && make develop
[mfdata:~] $ plugin_env
⌁plugin_env: test_plugin⌁[mfdata:~/test_plugin] $ echo $PYTHONPATH | grep python3_scientific/lib
⌁plugin_env: test_plugin⌁[mfdata:~/test_plugin] $ echo $?
1
# python3_scientific not in the PYTHONPATH for the plugin
# so impossible to import librairies from python3_scientific
⌁plugin_env: test_plugin⌁[mfdata:~/test_plugin] $ cat .layerapi2_dependencies 
python3@mfext
root@mfdata
-python3_scientific_core@mfext
-python3_devtools@mfext
-python3_ia@mfext
-python3_vim@mfext
-scientific_core@mfext
-python3_scientific_core@mfext
-python3_scientific@mfext
```

**Comment by matthieumarrast** [comment]
it seems the `.configuration_cache` file is generated in the plugin directory with a wrong PYTHONPATH, not taking into account all the loaded layers.
```
$plugin_wrapper --cwd --bash-cmds <plugin> NOTUSED
# python3_scientific not in pythonpath
$plugin_wrapper --cwd --bash-cmds --ignore-cache <plugin> NOTUSED
# python3_scientific in pythonpath
```

**Comment by matthieumarrast** [comment]
Today 15/09/2022 I got this issue again.
I'll try to figure out why this `.configuration_cache` file always contains a wrong PYTHONPATH, not the expected one.

The best workaround solution today I found is:
```
$ rm .configuration_cache
# ensure layer is loaded in your module env (mfserv, mfdata..)
$ layers | grep devtools
- (*) devtools@mfext [/opt/metwork-mfext-2.0/opt/devtools]
- (*) python3_devtools@mfext [/opt/metwork-mfext-2.0/opt/python3_devtools]
$ env | grep PYTHONPATH | sed 's/:/\n/g' | grep devtools
/opt/metwork-mfext-2.0/opt/python3_devtools/lib/python3.9/site-packages
/opt/metwork-mfext-2.0/opt/python3_devtools/lib
# go to plugin env 
$ plugin_env
# check layer is now in plugin python path
$ env | grep PYTHONPATH | sed 's/:/\n/g' | grep devtools
/opt/metwork-mfext-2.0/opt/python3_devtools/lib/python3.9/site-packages
/opt/metwork-mfext-2.0/opt/python3_devtools/lib
```
It generates the right PYTHONPATH for your plugin.

Another easiest workaround:
```
# outside plugin env
$ rm .configuration_cache
$ make develop
$ plugin_env
```

**Comment by matthieumarrast** [comment]
To reproduce :

```
$ layer_unload python3_devtools@mfext
[DEBUG]: unloading python3_devtools@mfext[/opt/metwork-mfext-2.0/opt/python3_devtools

$ layers | grep devtools
- (*) devtools@mfext [/opt/metwork-mfext-2.0/opt/devtools]
- python3_devtools@mfext [/opt/metwork-mfext-2.0/opt/python3_devtools]
$ # => python3_devtools is not loaded

$ env | grep PYTHONPATH | sed 's/:/\n/g' | grep devtools
$ # no python3_devtools in the PYTHONPATH

$ bootstrap_plugin.py create foobar --no-input
$ cd foobar
$ plugin_env

$ layers | grep devtools
- (*) devtools@mfext [/opt/metwork-mfext-2.0/opt/devtools]
- (*) python3_devtools@mfext [/opt/metwork-mfext-2.0/opt/python3_devtools]
$ # => loaded

$ env | grep PYTHONPATH | sed 's/:/\n/g' | grep devtools
$ # no python3_devtools in the PYTHONPATH !!!!
```

Another **workaround**, reload layer in plugin env, it will rebuild the python path:
```
$ layer_unload python3_devtools@mfext
[DEBUG]: unloading python3_devtools@mfext[/opt/metwork-mfext-2.0/opt/python3_devtools]
$ layer_load python3_devtools@mfext
[DEBUG]: loading python3_devtools@mfext[/opt/metwork-mfext-2.0/opt/python3_devtools]

$ env | grep PYTHONPATH | sed 's/:/\n/g' | grep devtools
PYTHONPATH=/opt/metwork-mfext-2.0/opt/python3_devtools/lib/python3.9/site-packages
/opt/metwork-mfext-2.0/opt/python3_devtools/lib
```

Another **workaround**, just after bootstraping a new plugin, always run `make develop` before `plugin_env`.

**Comment by matthieumarrast** [comment]
Kind of same issue with configuration name update:

If I update the configuration name in `/etc/metwork.config` variable environnent (with overwritten settings set in `/etc/metwork.config.d/<module>/plugins/<plugin>.ini`, then restart the \<module>, the variables are not updated in the plugin environment, according to the configuration name.

How to reproduce:

- initial state:

`/etc/metwork.confìg`:
```
DEV
```

`/etc/metwork.config.d/<module>/plugins/<plugin>.ini`
```
[custom]
foo[DEV]=bar
foo[INT]=toto
```
=> variable value in plugin env: MFSERV_CURRENT_PLUGIN_CUSTOM_FOO=bar

- Edit configuration name

`/etc/metwork.confìg`:
```
INT
```
- Restart service
```
sudo service metwork restart <module>
```

=> variable value in plugin env: MFSERV_CURRENT_PLUGIN_CUSTOM_FOO=bar
(instead of "toto")

solution: remove `.configuration_cache` and reexecute `plugin_env`

@thefab please save us ;-)

**Comment by thefab** [comment]
> Kind of same issue with configuration name update:
> 
> If I update the configuration name in `/etc/metwork.config` variable environnent (with overwritten settings set in `/etc/metwork.config.d/<module>/plugins/<plugin>.ini`, then restart the <module>, the variables are not updated in the plugin environment, according to the configuration name. [...]

not the same issue! But I just probably fixed it in mfplugin.

**Comment by matthieumarrast** [comment]
> > Kind of same issue with configuration name update:
> > If I update the configuration name in `/etc/metwork.config` variable environnent (with overwritten settings set in `/etc/metwork.config.d/<module>/plugins/<plugin>.ini`, then restart the , the variables are not updated in the plugin environment, according to the configuration name. [...]
> 
> not the same issue! But I just probably fixed it in mfplugin.

thank you !

**Comment by matthieumarrast** [comment]
tested **OK** with image `metwork/mfxxx-centos8-buildimage:integration`
I feel that not caching the plugin's pythonpath solve this entire issue and not only a big part
